/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        navy: "#0D2B45",
        "navy-deep": "#0D2B45",
        "navy-2": "#0D1F2D",
        "footer-navy": "#0D1F2D",
        medical: "#1B6B9A",
        "clinical-blue": "#1B6B9A",
        cyan: "#5B9EC9",
        "sky-mid": "#5B9EC9",
        softblue: "#E0EEF7",
        ice: "#E0EEF7",
        frost: "#E0EEF7",
        mist: "#F5F7F9",
        "off-white": "#F5F7F9",
        muted: "#2C4A5E",
        slate: "#2C4A5E",
        borderblue: "#E0EEF7",
        gold: "#C9A84C",
        "prestige-gold": "#C9A84C",
        alert: "#D4534A",
        "alert-red": "#D4534A",
      },
      fontFamily: {
        heading: ["var(--font-serif)", "Cormorant Garamond", "Georgia", "serif"],
        body: ["var(--font-sans)", "DM Sans", "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["52px", { lineHeight: "1", letterSpacing: "-0.02em", fontWeight: "300" }],
        h1: ["36px", { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "400" }],
        h2: ["26px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "400" }],
        h3: ["20px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "400" }],
        h4: ["16px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        eyebrow: ["11px", { lineHeight: "1.4", letterSpacing: "0.14em", fontWeight: "500" }],
        "body-lg": ["17px", { lineHeight: "1.7", letterSpacing: "0", fontWeight: "300" }],
        body: ["15px", { lineHeight: "1.75", letterSpacing: "0", fontWeight: "300" }],
        "body-sm": ["13px", { lineHeight: "1.65", letterSpacing: "0", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        micro: ["11px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "400" }],
        button: ["13px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "400" }],
        nav: ["14px", { lineHeight: "1", letterSpacing: "0", fontWeight: "300" }],
      },
      boxShadow: {
        premium: "0 30px 90px rgba(13, 43, 69, 0.12)",
        soft: "0 4px 16px rgba(13, 43, 69, 0.06)",
        glass: "0 24px 80px rgba(13, 43, 69, 0.12)",
      },
      borderRadius: {
        xs: "8px",
        sm: "12px",
        card: "20px",
        panel: "24px",
        pill: "100px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        "2xl": "80px",
        "3xl": "120px",
        "4xl": "160px",
      },
      backgroundImage: {
        "clinic-radial":
          "radial-gradient(circle at 16% 12%, rgba(91, 158, 201, 0.12), transparent 30%), radial-gradient(circle at 50% 100%, rgba(224, 238, 247, 0.45), transparent 34%)",
      },
    },
  },
  plugins: [],
};
